### ISSUE TITLE
Permit adding overlays from vscode file manager

### ISSUE THREAD

**Issue by vincenzoml** [niivue/niivue-vscode#10]
Hi, thanks for this effort on niivue, it's amazing. It's especially useful when working in remote servers, to visualize images without downloading them locally.

However: I use vscode-remote, images are opened quite well in niivue, but to add an overlay I first have to download it because when I click add overlay, it opens a file browser to open a local file. I would like to be able to open files from vscode file browser (maybe via drag and drop?).

**Comment by korbinian90** [comment]
Thanks for the feedback!

The remote issue was a bug and should be fixed in version 0.3.2. Now even in remote a remote-filepicker should open. I hope this resolves the issue for you.

I might try to add a context menu, so that when right clicking a file there would be the option: Add as overlay
