### ISSUE TITLE
Feature request: add overlays

### ISSUE THREAD

**Issue by vincenzoml** [niivue/niivue-vscode#4]
Would be great to be able to add overlays, that's it.

**Comment by korbinian90** [comment]
At the moment the extension works as a "readonly editor" for a file. So currently, it gets only the input of one file.
I think I can create a custom command: "Open NiiVue Panel" and make it persistent.
Clicked files could be forwarded to this panel, when it is selected. The first image would be greyscale and the second image added in opaque colormap.

The data is read from disk by vscode and sent to niivue as a buffer. This is what happens in the rendered niivue html document:
```javascript
let image = new niivue.NVImage(data, uri);
nv.addVolume(image);
```
Is there a way to use addVolume and set a colormap?

**Comment by korbinian90** [comment]
**update v0.2.0**
- new button to select a second image to load as overlay with `redyell` colormap
