### ISSUE TITLE
Feature request: display metadata

### ISSUE THREAD

**Issue by ubless607** [niivue/niivue-vscode#6]
This extension is awesome! Keep up the great work :)

Feautre request: Display metadata (dimensions, data resolution, value)

**Comment by korbinian90** [comment]
Thank you for the positive feedback and the feature request :)

We will try to add these features. I'm also missing the meta data currently and showing the value at the cursor or cross.

**Comment by korbinian90** [comment]
**update 0.1.4**
- Datatype, matrix size and voxel size is now displayed

value under cursor/cross is still work in progress

**Comment by ubless607** [comment]
@korbinian90 Definitely love the new feature!
As now, if user clicks the image, the metadata(Datatype, matrix size and voxel size) is gone. Will it always be visible?
Also, it would be great if the orientation can also be displayed (e.g, RAS+).

**Comment by korbinian90** [comment]
> As now, if user clicks the image, the metadata(Datatype, matrix size and voxel size) is gone. Will it always be visible?

It should be always visible, at least it is on my machine.. There is probably something not ideal in the html layout

**Comment by ubless607** [comment]
@korbinian90 Sorry, the scroll bar was moved down.

**Comment by korbinian90** [comment]
Ah, thanks for testing again ;)
Maybe I can make it adaptive in size..
